"""Add categoryType

Revision ID: 66bba62c67cc
Revises: 8b09bfafc83f
Create Date: 2025-07-23 08:03:54.498602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bba62c67cc'
down_revision = '8b09bfafc83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
