"""Make name+type unique together

Revision ID: aed15d1dddac
Revises: cd4e2c8192fd
Create Date: 2025-07-30 09:21:22.868324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed15d1dddac'
down_revision = 'cd4e2c8192fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.create_unique_constraint('uq_category_name_type', ['name', 'type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_name_type', type_='unique')
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
